name: Create release

on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build x86-64 mainnet
        run: |
          mkdir artifacts
          git fetch -a
          mvn clean compile package -DskipTests
          cp target/MyLocalTon.jar artifacts/MyLocalTon-x86-64.jar

      - name: Build x86-64 testnet
        run: |
          mvn clean compile package -DskipTests -Dton_branch=testnet
          cp target/MyLocalTon.jar artifacts/MyLocalTon-x86-64-testnet.jar

      - name: Build arm64-aarch64 mainnet
        run: |
          git checkout arm64-aarch64
          mvn clean compile package -DskipTests
          cp target/MyLocalTon.jar artifacts/MyLocalTon-arm64.jar

      - name: Build arm64-aarch64 testnet
        run: |
          mvn clean compile package -DskipTests -Dton_branch=testnet
          cp target/MyLocalTon.jar artifacts/MyLocalTon-arm64-testnet.jar

      - name: Checkout main branch
        run: |
          git checkout main
          ls artifacts

      - name: Read CHANGELOG.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(cat CHANGELOG.md)
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"
          echo "::set-output name=CHANGELOG_BODY::$r"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: MyLocalTon v${{ github.run_number }}
          body: |
            ${{ steps.read_release.outputs.CHANGELOG_BODY }}
          draft: false
          prerelease: true

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/*.jar
          tag: v${{ github.run_number }}
          overwrite: true
          file_glob: true
